# Generated by Django 4.1.2 on 2023-01-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_customer_cdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ccexp',
            field=models.CharField(default='02/25', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='ccno',
            field=models.CharField(default='04359862', max_length=255),
        ),
    ]
